[package]
name = "chipcalc_native_rust"
version = "0.1.0"
authors = ["djdisodo <djdisodo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_reverse = "0.1.8"
num-traits = "0.2"
num-derive = "0.2"
